baseURL = "https://playground.l882.nl"
languageCode = "en-us"
title = "Geeks and Freaks"
theme = "hyde"
publishDir = "docs"

[params]
  themeColor = "theme-base-0d"
  description = "Same random notes and ramblings by Maikel"
