baseURL = "https://notes.l882.nl/"
languageCode = "en-us"
title = "Random notes by Maikel"
theme = "hyde"
publishDir = "docs"
[params]
  description = "Same random notes"

[[menu.main]]
    name = "CLI notes and fu"
    url = "/cli/"
    weight = 1

[[menu.main]]
    name = "Configuration"
    url = "/configuration/"
    weight = 2

[[menu.main]]
    name = "Hugo"
    url = "/hugo/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


