baseURL = "https://playground.l882.nl/"
languageCode = "en-us"
title = "Random notes by Maikel"
theme = "hyde"
publishDir = "docs"
[params]
  description = "Same random notes"

[[menu.main]]
    name = "CLI and configuration pastes"
    url = "/cli/"
    weight = 1

[[menu.main]]
    name = "Hugo"
    url = "/hugo/"
    weight = 2 
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


